"""initial schema

Revision ID: 8936d3228de3
Revises: 
Created: 2026-08-05 18:48:31.732670
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8936d3228de3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_key', sa.String(length=300), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('normalized_name', sa.String(length=400), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('street_address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('niche_key', sa.String(length=60), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_status', sa.String(length=40), nullable=True),
    sa.Column('is_chain', sa.Boolean(), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_location', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name=op.f('ck_businesses_rating_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses')),
    sa.UniqueConstraint('dedupe_key', name='uq_businesses_dedupe_key'),
    sa.UniqueConstraint('source_key', name='uq_businesses_source_key')
    )
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index('ix_businesses_city_state', 'businesses', ['city', 'state'], unique=False)
    op.create_index(op.f('ix_businesses_county'), 'businesses', ['county'], unique=False)
    op.create_index(op.f('ix_businesses_created_at'), 'businesses', ['created_at'], unique=False)
    op.create_index(op.f('ix_businesses_email'), 'businesses', ['email'], unique=False)
    op.create_index(op.f('ix_businesses_first_discovered_at'), 'businesses', ['first_discovered_at'], unique=False)
    op.create_index(op.f('ix_businesses_google_place_id'), 'businesses', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_businesses_niche_key'), 'businesses', ['niche_key'], unique=False)
    op.create_index('ix_businesses_niche_state', 'businesses', ['niche_key', 'state'], unique=False)
    op.create_index('ix_businesses_no_website', 'businesses', ['niche_key', 'city'], unique=False, postgresql_where=sa.text('website_url IS NULL'))
    op.create_index(op.f('ix_businesses_normalized_name'), 'businesses', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_businesses_phone_e164'), 'businesses', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_index(op.f('ix_businesses_website_domain'), 'businesses', ['website_domain'], unique=False)
    op.create_index(op.f('ix_businesses_zip_code'), 'businesses', ['zip_code'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('destination', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('remote_ref', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_index(op.f('ix_export_jobs_created_at'), 'export_jobs', ['created_at'], unique=False)
    op.create_table('geo_places',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('zips', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_places')),
    sa.UniqueConstraint('normalized_name', 'state', 'country_code', name='uq_geo_places_name_state')
    )
    op.create_index(op.f('ix_geo_places_county'), 'geo_places', ['county'], unique=False)
    op.create_index('ix_geo_places_county_state', 'geo_places', ['county', 'state'], unique=False)
    op.create_index(op.f('ix_geo_places_name'), 'geo_places', ['name'], unique=False)
    op.create_index(op.f('ix_geo_places_normalized_name'), 'geo_places', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_geo_places_population'), 'geo_places', ['population'], unique=False)
    op.create_index(op.f('ix_geo_places_state'), 'geo_places', ['state'], unique=False)
    op.create_index('ix_geo_places_state_population', 'geo_places', ['state', 'population'], unique=False)
    op.create_table('geocode_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(length=400), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('viewport', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geocode_cache')),
    sa.UniqueConstraint('query', name=op.f('uq_geocode_cache_query'))
    )
    op.create_index(op.f('ix_geocode_cache_created_at'), 'geocode_cache', ['created_at'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'partial', 'cancelled', name='run_status', native_enum=False, length=40), nullable=False),
    sa.Column('location_key', sa.String(length=80), nullable=True),
    sa.Column('niche_keys', sa.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('target_leads', sa.Integer(), nullable=False),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('new_businesses', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('audited', sa.Integer(), nullable=False),
    sa.Column('scored', sa.Integer(), nullable=False),
    sa.Column('qualified', sa.Integer(), nullable=False),
    sa.Column('enriched', sa.Integer(), nullable=False),
    sa.Column('api_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_runs_date_status', 'pipeline_runs', ['run_date', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_run_date'), 'pipeline_runs', ['run_date'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('robots_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_robots_cache')),
    sa.UniqueConstraint('host', name=op.f('uq_robots_cache_host'))
    )
    op.create_index(op.f('ix_robots_cache_created_at'), 'robots_cache', ['created_at'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=400), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressions')),
    sa.UniqueConstraint('kind', 'value', name='uq_suppressions_kind_value')
    )
    op.create_index(op.f('ix_suppressions_created_at'), 'suppressions', ['created_at'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('opportunity', sa.Text(), nullable=True),
    sa.Column('redesign_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outreach_angle', sa.Text(), nullable=True),
    sa.Column('outreach_subject', sa.String(length=300), nullable=True),
    sa.Column('talking_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inferred_niche', sa.String(length=60), nullable=True),
    sa.Column('estimated_value_tier', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_ai_insights_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_ai_insights_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insights'))
    )
    op.create_index(op.f('ix_ai_insights_business_id'), 'ai_insights', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_created_at'), 'ai_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_input_hash'), 'ai_insights', ['input_hash'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_contacts_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('business_id', 'kind', 'value', name='uq_contacts_business_kind_value')
    )
    op.create_index(op.f('ix_contacts_business_id'), 'contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('lead_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_path', sa.Text(), nullable=True),
    sa.Column('csv_path', sa.Text(), nullable=True),
    sa.Column('excel_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_daily_reports_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reports')),
    sa.UniqueConstraint('report_date', name='uq_daily_reports_report_date')
    )
    op.create_index(op.f('ix_daily_reports_created_at'), 'daily_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('website_status', sa.Enum('no_website', 'broken', 'poor', 'outdated', 'average', 'good', 'unknown', name='website_status', native_enum=False, length=40), nullable=False),
    sa.Column('website_score', sa.Float(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'qualified', 'contacted', 'responded', 'meeting_booked', 'proposal_sent', 'won', 'lost', 'disqualified', 'do_not_contact', name='lead_status', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_attempts', sa.Integer(), nullable=False),
    sa.Column('last_contact_channel', sa.String(length=40), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(length=200), nullable=True),
    sa.Column('deal_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('first_scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name=op.f('ck_leads_priority_range')),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_leads_score_range')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_leads_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('business_id', name=op.f('uq_leads_business_id'))
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_follow_up_at'), 'leads', ['follow_up_at'], unique=False)
    op.create_index(op.f('ix_leads_last_scored_at'), 'leads', ['last_scored_at'], unique=False)
    op.create_index(op.f('ix_leads_qualified'), 'leads', ['qualified'], unique=False)
    op.create_index('ix_leads_qualified_score', 'leads', ['qualified', 'score'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_score', 'leads', ['status', 'score'], unique=False)
    op.create_table('website_audits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('ok', 'dns_failure', 'connection_refused', 'timeout', 'tls_error', 'http_error', 'parked', 'blocked', 'skipped_robots', 'error', name='audit_outcome', native_enum=False, length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('uses_https', sa.Boolean(), nullable=False),
    sa.Column('ssl_valid', sa.Boolean(), nullable=False),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mixed_content', sa.Boolean(), nullable=False),
    sa.Column('mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('has_viewport_meta', sa.Boolean(), nullable=False),
    sa.Column('horizontal_overflow', sa.Boolean(), nullable=False),
    sa.Column('psi_performance', sa.Float(), nullable=True),
    sa.Column('psi_seo', sa.Float(), nullable=True),
    sa.Column('psi_accessibility', sa.Float(), nullable=True),
    sa.Column('psi_best_practices', sa.Float(), nullable=True),
    sa.Column('lcp_ms', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('tbt_ms', sa.Float(), nullable=True),
    sa.Column('page_weight_kb', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('copyright_year', sa.Integer(), nullable=True),
    sa.Column('has_structured_data', sa.Boolean(), nullable=False),
    sa.Column('has_sitemap', sa.Boolean(), nullable=False),
    sa.Column('has_contact_form', sa.Boolean(), nullable=False),
    sa.Column('has_click_to_call', sa.Boolean(), nullable=False),
    sa.Column('has_cta', sa.Boolean(), nullable=False),
    sa.Column('broken_link_count', sa.Integer(), nullable=False),
    sa.Column('images_missing_alt', sa.Integer(), nullable=False),
    sa.Column('tech_stack', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('design_era', sa.String(length=40), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('screenshot_mobile_path', sa.Text(), nullable=True),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('no_website', 'broken', 'poor', 'outdated', 'average', 'good', 'unknown', name='website_status', native_enum=False, length=40), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_website_audits_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_website_audits_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_audits'))
    )
    op.create_index('ix_website_audits_business_checked', 'website_audits', ['business_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_website_audits_checked_at'), 'website_audits', ['checked_at'], unique=False)
    op.create_index(op.f('ix_website_audits_created_at'), 'website_audits', ['created_at'], unique=False)
    op.create_index('ix_website_audits_status', 'website_audits', ['status'], unique=False)
    op.create_table('website_status_changes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.Enum('no_website', 'broken', 'poor', 'outdated', 'average', 'good', 'unknown', name='website_status', native_enum=False, length=40), nullable=True),
    sa.Column('new_status', sa.Enum('no_website', 'broken', 'poor', 'outdated', 'average', 'good', 'unknown', name='website_status', native_enum=False, length=40), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=True),
    sa.Column('old_url', sa.Text(), nullable=True),
    sa.Column('new_url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_website_status_changes_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_status_changes'))
    )
    op.create_index(op.f('ix_website_status_changes_business_id'), 'website_status_changes', ['business_id'], unique=False)
    op.create_index(op.f('ix_website_status_changes_created_at'), 'website_status_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_website_status_changes_detected_at'), 'website_status_changes', ['detected_at'], unique=False)
    op.create_table('lead_score_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('website_score', sa.Float(), nullable=True),
    sa.Column('website_status', sa.Enum('no_website', 'broken', 'poor', 'outdated', 'average', 'good', 'unknown', name='website_status', native_enum=False, length=40), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_score_history_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_lead_score_history_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_score_history'))
    )
    op.create_index(op.f('ix_lead_score_history_lead_id'), 'lead_score_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_score_history_recorded_at'), 'lead_score_history', ['recorded_at'], unique=False)
    op.create_table('outreach_activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=60), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_outreach_activities_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_activities'))
    )
    op.create_index(op.f('ix_outreach_activities_created_at'), 'outreach_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_activities_lead_id'), 'outreach_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_activities_occurred_at'), 'outreach_activities', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_activities_occurred_at'), table_name='outreach_activities')
    op.drop_index(op.f('ix_outreach_activities_lead_id'), table_name='outreach_activities')
    op.drop_index(op.f('ix_outreach_activities_created_at'), table_name='outreach_activities')
    op.drop_table('outreach_activities')
    op.drop_index(op.f('ix_lead_score_history_recorded_at'), table_name='lead_score_history')
    op.drop_index(op.f('ix_lead_score_history_lead_id'), table_name='lead_score_history')
    op.drop_table('lead_score_history')
    op.drop_index(op.f('ix_website_status_changes_detected_at'), table_name='website_status_changes')
    op.drop_index(op.f('ix_website_status_changes_created_at'), table_name='website_status_changes')
    op.drop_index(op.f('ix_website_status_changes_business_id'), table_name='website_status_changes')
    op.drop_table('website_status_changes')
    op.drop_index('ix_website_audits_status', table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_created_at'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_checked_at'), table_name='website_audits')
    op.drop_index('ix_website_audits_business_checked', table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_index('ix_leads_status_score', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index('ix_leads_qualified_score', table_name='leads')
    op.drop_index(op.f('ix_leads_qualified'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_scored_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_follow_up_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_created_at'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_business_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_ai_insights_input_hash'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_created_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_business_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_suppressions_created_at'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_robots_cache_created_at'), table_name='robots_cache')
    op.drop_table('robots_cache')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_run_date'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_date_status', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_geocode_cache_created_at'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    op.drop_index('ix_geo_places_state_population', table_name='geo_places')
    op.drop_index(op.f('ix_geo_places_state'), table_name='geo_places')
    op.drop_index(op.f('ix_geo_places_population'), table_name='geo_places')
    op.drop_index(op.f('ix_geo_places_normalized_name'), table_name='geo_places')
    op.drop_index(op.f('ix_geo_places_name'), table_name='geo_places')
    op.drop_index('ix_geo_places_county_state', table_name='geo_places')
    op.drop_index(op.f('ix_geo_places_county'), table_name='geo_places')
    op.drop_table('geo_places')
    op.drop_index(op.f('ix_export_jobs_created_at'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_businesses_zip_code'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_website_domain'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_phone_e164'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_name'), table_name='businesses')
    op.drop_index('ix_businesses_no_website', table_name='businesses', postgresql_where=sa.text('website_url IS NULL'))
    op.drop_index('ix_businesses_niche_state', table_name='businesses')
    op.drop_index(op.f('ix_businesses_niche_key'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_google_place_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_first_discovered_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_email'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_county'), table_name='businesses')
    op.drop_index('ix_businesses_city_state', table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
